Create database PROYECTOSMD ;
USE PROYECTOSMD ;


#------TABLAS -------


CREATE TABLE ROLES 
(
		ID_E INTEGER NOT NULL AUTO_INCREMENT,
        NOMBRE VARCHAR(15),
        FECHA_DE_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        primary key(ID_E)

);



CREATE TABLE USUARIOS
(
		ROLLID INTEGER(5),
        USERID INTEGER auto_increment,
		NOMBRE_USUARIO VARCHAR(50),
        CLAVE VARCHAR(20),
        PRIMARY KEY (USERID),
        FOREIGN KEY (ROLLID) REFERENCES ROLES(ID_E)
);

-- MODIFICAR -- 

CREATE TABLE DOCTORES
(
	DOC_ID INTEGER NOT null auto_increment,
    Nombre varchar(15), 
    apellido varchar(15),
    cedula VARCHAR(12) unique,
    telefono integer,
    NO_DECRETO integer,
    No_registro integer,
    especialidad varchar(25),
    USERID INTEGER,
    primary key (DOC_ID),
    foreign key (USERID) REFERENCES USUARIOS (USERID)
    
);


CREATE TABLE PACIENTES
(
		PACIENTEID integer NOT NULL auto_increment,
		NOMBRE VARCHAR(50),
        APELLIDO VARCHAR(50),
        CEDULA varchar(12) UNIQUE,
        EDAD INT(3),
        TIPO_SANGRE VARCHAR(12),
        SEXO VARCHAR(50),
        TEL_EMERGENCIA VARCHAR(20),      
        DOC_ID INTEGER(5),
        DISPOSITIVO_MEDICO varchar(12),
        ENFERMEDADES_FRECUENTES VARCHAR(1000),
        MEDICAMENTOS_RECETADOS varchar(1000),
        FECHA_DE_INGRESO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (PACIENTEID),
        foreign key(DOC_ID) references DOCTORES(DOC_ID)
);


INSERT INTO ROLES (NOMBRE) VALUES ('DOCTOR');

INSERT INTO USUARIOS (ROLLID, NOMBRE_USUARIO, CLAVE)
 VALUES(1,'Xramirez','123456789');

INSERT INTO DOCTORES (NOMBRE, APELLIDO, CEDULA, NO_DECRETO, NO_REGISTRO, ESPECIALIDAD)
VALUES ('Xiolin', 'Ramirez', '00100525260', 2002,2003, 'Medico General');

INSERT INTO PACIENTES (NOMBRE, APELLIDO, CEDULA, EDAD, TIPO_SANGRE, SEXO, TEL_EMERGENCIA, DOC_ID, DISPOSITIVO_MEDICO,ENFERMEDADES_FRECUENTES,MEDICAMENTOS_RECETADOS)
VALUES ('BRIAN', 'VASQUEZ','0020003350', 21, 'o+', 'M','8094567895' , 1, 'Marcapasos', 'ATAQUES AL CORAZON', 'ASPIRINAS');

INSERT INTO PACIENTES (NOMBRE, APELLIDO, CEDULA, EDAD, TIPO_SANGRE, SEXO, TEL_EMERGENCIA, DOC_ID, DISPOSITIVO_MEDICO,ENFERMEDADES_FRECUENTES,MEDICAMENTOS_RECETADOS)
VALUES ('Antonio', 'Lorenzo','22301418053', 24, 'o+', 'M','8492859050' , 1, 'Marcapasos', 'ATAQUES AL CORAZON', 'ASPIRINAS');


#------REGISTROS-------
DESCRIBE ROLES;
DESCRIBE USUARIOS;
DESCRIBE DOCTORES;
DESCRIBE PACIENTES;
DESCRIBE CONSULTA;

SELECT*FROM ROLES;
SELECT*FROM USUARIOS;
SELECT*FROM DOCTORES;
SELECT*FROM PACIENTES;


















